mundipagg/amora-data-build-tool

amora/models.py
amora/tests/assertions.py
amora/transformations.py
tests/test_assertions.py
tests/test_transformations.py

- ✨ Adiciona `amora.transaformations.parse_numbers`
- 🐛 Corrige `amora.tests.assertions.is_numeric`
- ✨ Refatora `amora.tests.assertions.that` para permitir que um teste retorne falso ao invés de levantar a excessão `pytest.Fail`

Adiciona `amora.transaformations.parse_numbers`

---

amora/tests/assertions.py
tests/test_assertions.py

- ✨ Adiciona `amora.tests.assertions.is_a_non_empty_string`
- 🧪 Aumenta cobertura de testes

Adiciona validação `is_a_non_empty_string`

---

.github/workflows/main.yaml
.github/workflows/pull-request.yaml
amora/cli.py
amora/config.py
amora/contracts.py
amora/models.py
amora/providers/bigquery.py
amora/storage.py
amora/tests/assertions.py
amora/tests/audit.py
amora/tests/pytest_plugin.py
pyproject.toml
tests/providers/test_bigquery.py

O processo de materialização gera 2 tipos de custos: custo de escanear os dados [1] a serem transformados e o custo de armazenar [2] esses dados para modelos materializados como `MaterializationTypes.table`. No BQ os custos hoje são definidos da seguinte forma: 
1-  Custo de query é definido hoje por $5 por TB
2- Custo de armazenamento é definido por $0.020 por GB/mês
Cada data assertion é uma query sql. Cada query SQL, se executada em dados persistidos no BQ, incorre em billable bytes. No amora, cada query executada com `amora.providers.bigquery.run` resulta em um `RunResult` ou em um `DryRunResult`. Em ambos os casos, temos o total de bytes processados pelo BQ. A partir disso, podemos calcular quanto o BQ nos cobra, usando a fórmula de billing de [5 Bidens por …

DTREX-414 e DTREX-415 :: estimated query/storage cost

---

poetry.lock
pyproject.toml

- Updates jinja2^3.0.3
- Removes dbt-bigquery from dev-dependencies

Updates jinja2^3.0.3 and removes dbt-bigquery

---

.github/workflows/main.yaml
.github/workflows/pull-request.yaml
amora/cli.py
amora/compilation.py
amora/config.py
amora/logger.py
amora/models.py
amora/providers/bigquery.py
amora/tests/assertions.py
amora/tests/audit.py
amora/tests/pytest_plugin.py
amora/utils.py
examples/amora_project/models/heart_rate_over_100.py
pyproject.toml
tests/cli/test_materialize.py
tests/models/heart_rate_over_100.py
tests/providers/test_bigquery.py
tests/test_assertions.py
tests/test_compilation.py
tests/test_materialization.py

- 🐛 Corrige implementação de `amora.providers.bigquery.dry_run` que falhava ao ser executado em modelos sem source, que referenciam uma tabela
- 🎨 Remove regra de `line-length` customizada da verificação do black
- ✨ Adiciona logger e verbosidade ao tentar compilar um modelo com erro sintático

Fix: DTREX-560 :: dry run

---

amora/providers/bigquery.py
poetry.lock
pyproject.toml
tests/providers/test_bigquery.py
tests/test_compilation.py

- ⬆️ pytest 6.2.5 -> 7.1.1
- ⬆️ mypy 0.910 -> 0.941
- ⬆️ sqlparse 0.3.1 -> 0.4.2
- ⬆️ mkdocstring 0.16.2 -> 0.18.1
- ⬆️ mkdocs-autorefs 0.3.8 -> 0.4.1
- ⬆️ black 21.12b0 -> 22.1.0

Atualiza dependências python

---

amora/models.py
amora/providers/bigquery.py
amora/tests/assertions.py
amora/tests/generic_tests.py
amora/transformations.py
examples/amora_project/models/health.py
examples/amora_project/models/heart_agg.py
examples/amora_project/models/heart_rate.py
examples/amora_project/models/heart_rate_over_100.py
examples/amora_project/models/steps.py
examples/amora_project/models/steps_agg.py
examples/amora_project/tests/test_models_schema.py
tests/models/health.py
tests/models/heart_agg.py
tests/models/heart_rate_over_100.py
tests/providers/test_bigquery.py

- ✨ Adiciona função para inferir o schema do BigQuery de um modelo amora
- ✨ Adiciona função para descobrir o schema do BigQuery a partir do _classmethod_ `source` de um modelo amora
- ✨ Adiciona função para descobrir o schema de um modelo amora materializado
- 🐛 Corrige schemas e adiciona documentação a modelos de exemplo/teste
- 🧪 Adiciona testes genéricos, que podem ser reutilizados por múltiplos projetos
- `test_materialized_schema_equal_local_schema`: Teste garante que o modelo materializado como view/tabela tem o mesmo schema do modelo definido localmente.
- `test_models_schema_equal_its_source_schema`: Teste que garante que o modelo definido localmente tem o mesmo schema do que o resultado de `source`, query responsável por materializá-lo.
Testes pytest que podem (devem?) ser …

Validação automática de schemas de modelos

---

amora/cli.py
amora/feature_store/config.py
amora/feature_store/logging.py
pyproject.toml

-  ✨ Adds the possibility of using tqdm ASCII logging through feast monkeypatch and `AMORA_FEATURE_STORE_TQDM_ASCII_LOGGING` and `AMORA_FEATURE_STORE_TQDM_DISABLE` config

`AMORA_FEATURE_STORE_TQDM_ASCII_LOGGING` and `AMORA_FEATURE_STORE_TQDM_DISABLE`

---

amora/cli/feature_store.py
amora/feature_store/__init__.py
amora/feature_store/config.py
amora/feature_store/usage_tracking.py
pyproject.toml
tests/feature_store/test_usage_tracking.py

- 🐛 Makes feast usage tracking opt-in. Default: No tracking
- ✨ Enables a custom destination for feature store related (error tracking, usage statistic collection and time profiling) tracking through `AMORA_FEATURE_STORE_USAGE_TRACKING_ENABLED` and `AMORA_FEATURE_STORE_USAGE_ENDPOINT`

DTREX-649 Makes feast usage tracking opt-in. Default: No tracking

---

amora/dash/app.py
amora/dash/authentication.py
amora/dash/config.py
poetry.lock
pyproject.toml

- feat(dash): Adds Authlib>=1.0; updates dash==2.5.1
- feat(dash): Adds `amora.dash.authentication` with Auth0 integration for authentication
To enable auth0 authentication through `/login`, the following environment variables must be available:
```
AMORA_DASH_AUTH0_CLIENT_ID=AClientId
AMORA_DASH_AUTH0_CLIENT_SECRET=TheSuperSecretKey
AMORA_DASH_AUTH0_DOMAIN=something.us.auth0.com
```
Generating a `AMORA_DASH_APP_SECRET_KEY` with e.g. `openssl rand -hex 32` is also recommended.
---
More on: https://auth0.com/docs/quickstart/webapp/python/01-login

DTREX-659 :: amora[dash] :: auth0 integration

---

amora/models.py

No need to try to interpret files prefixed with underscore (`_`)

fix(models): Performance improvement on `amora.models.list_models`

---

amora/dash/components/model_columns.py
amora/dash/components/model_datatable.py
amora/dash/components/model_labels.py
amora/dash/pages/feature_store.py
amora/logger.py
amora/providers/bigquery.py
examples/amora_project/models/step_count_by_source.py
tests/models/step_count_by_source.py

- feat(dash): Refactors `amora.dash.pages.feature_store` page
- Adds feature view icon
- Adds a `dash.DataTable` for feature data sample
- Adds columns description
- feat(dash): Adds column description and feature view icon to `step_count_by_source.py` model
- feat(dash): Adds `amora.dash.components.model_columns`, a component to render the model columns descriptions/documentation 
- feat(dash): Adds `amora.dash.components.model_labels`, a component to render the model labels (`amora.models.ModelConfig.labels`)
- feat(bigquery): Caches `amora.providers.bigquery.sample` results for 1 day
- feat(logger): Adds `amora.logger.log_execution`. The decorator wraps the execution of a function, calculates the execution time and logs the result in a human readable way
Table samples currently doesn't …

DTREX-686 :: amora[dash] :: `amora.dash.pages.feature_store` page refactor

---

amora/cli/models.py
amora/compilation.py
amora/providers/bigquery.py
amora/templates/new-model.py.jinja2
amora/tests/generic_tests.py
docs_src/providers/bigquery.md
examples/amora_project/models/record_repeated_field.py
poetry.lock
pyproject.toml
tests/cli/test_models_import.py
tests/providers/test_bigquery.py

- 🐛 fix(cli): Adds support for importing tables with repeated fields with `amora models import`
- ✨ feat(cli): Runs `shed` on files created by `amora models import`. Auto generated models now are auto formatted too
- 🎨 chore(bigquery): Renames data schema functions
- 📝 docs(bigquery): Improves `amora.providers.bigquery` documentation
- 🐛 fix(bigquery): Refactors type maps
- ✨ feat(bigquery): Adds the possibility for literal `AmoraModel` arrays
---
https://console.cloud.google.com/marketplace/product/city-of-austin/austin-crime
```sh
amora models import --table-reference bigquery-public-data.austin_crime.crime bigquery_public_data/austin_crime/crime 
```
Will result in `$AMORA_MODELS_PATH/bigquery_public_data/austin_crime/crime.py`
```python
from datetime import datetime
from sqlalchemy …
```

feat(cli): Adds support for importing tables with repeated fields in `amora models import`

---

amora/dash/components/model_labels.py
amora/dash/components/question_details.py
amora/dash/pages/dashboard.py
amora/dashboards.py
amora/models.py
amora/questions.py
amora/visualization.py
examples/amora_project/models/heart_rate.py
examples/amora_project/models/heart_rate_over_100.py
examples/amora_project/models/step_count_by_source.py
examples/amora_project/models/steps.py
tests/models/heart_rate.py
tests/models/heart_rate_over_100.py
tests/models/step_count_by_source.py
tests/models/steps.py
tests/test_materialization.py
tests/test_models.py

- 💥 feat!(models): Changes `amora.models.ModelConfig` interface from  `labels: Dict[str, str]` to `labels: Labels`
- ✨ feat(models): Adds select functions to filter models by labels
- `amora.models.select_models_with_labels`
- `amora.models.select_models_with_label_keys`
- 📢 refactor(models): Improves error messages for `amora.models.amora_model_for_path`
- 📢 fix(logs): Fixes `amora.models.list_models` logging on exception
- 🐛 fix(mypy): Typing related fixes
---
Enabler for: 
- `--labels` CLI option:
- `--labels freshness`: Selects all models with a `freshness` label key
- `--labels freshness:daily`: Selects all models with a `freshness` label key, and a `daily` value
- Clickable `amora.dash.components.model_label` component, that could render a filtered …

New API for model selection by labels and minor models iteration fixes

---

amora/dash/components/side_bar.py
amora/dash/pages/feature_store.py

O estilo `regular` só está disponível na versão paga do Font Awesome

fix: Corrige estilo dos icones

---

amora/dash/components/side_bar.py

A tecla para acionar o menu agora é `m`

fix: Corrige hotkey para acionar sidebar

---

amora/cli/typer_app.py
amora/dash/components/model_code.py
amora/models.py
amora/utils.py
tests/cli/test_materialize.py
tests/cli/test_models_import.py
tests/test_dag.py
tests/test_materialization.py
tests/test_models.py

- ♻️ refactor(models): Rewriters model import logic
- ♻️ refactor(models): `AmoraModel.model_file_path()` -> `AmoraModel.path()` 
- ♻️ refactor(models): `AmoraModel.target_path(model_file_path)` -> `AmoraModel.target_path()`
- 🧪 tests(models): Improves test coverage

refactor: Refatora descoberta de modelos

---

amora/dash/components/model_data_owner.py
amora/dash/components/model_details.py
amora/dash/pages/owners.py
amora/models.py
examples/amora_project/models/health.py
examples/amora_project/models/heart_agg.py
examples/amora_project/models/heart_rate.py
examples/amora_project/models/heart_rate_over_100.py
examples/amora_project/models/step_count_by_source.py
examples/amora_project/models/steps.py

- ✨ feat(models): Adds `amora.models.list_models_with_owner`
- ✨ feat(models): Adds `amora.models.owners_to_models_dict`
- ✨ feat(dash): Adds `/owners` page
- ✨ feat(dash): Adds "Data Owner" to the `amora.dash.components.model_details`
- ✨ feat(examples): Adds Data Owners to example models

DTREX-681 :: UI :: Data Owner

---

amora/cli/typer_app.py
amora/config.py

Sugestão de feature:
Possibilitar seleção de testes através de argumentos do `pytest`.

Feat: allow test selection

---

amora/feature_store/__init__.py
amora/feature_store/config.py

- 🐛 fix(feature-store): Removes `AMORA_FEATURE_STORE_REPO_PATH` configuration. `repo_path` [is optional](https://github.com/feast-dev/feast/blob/v0.29-branch/sdk/python/feast/repo_config.py#L152) and unused in amora

Removes `AMORA_FEATURE_STORE_REPO_PATH` configuration

---

amora/dash/components/model_data_owner.py
amora/dash/pages/owners.py
amora/providers/bigquery.py
amora/tests/assertions.py
examples/amora_project/models/heart_agg.py
tests/models/heart_agg.py
tests/models/heart_rate.py
tests/models/heart_rate_over_100.py
tests/models/step_count_by_source.py
tests/models/steps.py
tests/test_materialization.py

Esse PR remove os warnings do sqlalchemy

feat: Prepara código para API do sqlalchemy 2.0

---

amora/feature_store/decorators.py

Esse PR é apenas uma pequena melhoria para ajudar no _auto-complete_ de editores.
Conceitualmente, ainda há um trabalho maior a ser feito, porque de dentro do contexto `amora/feature_store` existe uma quebra de fronteiras (pensanddo nos tipos necessários para se trabalhar)

fix: Melhora tipagem em amora/feature_store/decorators.py
