- amora/tests/assertions.py
- pyproject.toml
- tests/test_assertions.py
-  🐛 [Corrige implementação de amora.tests.assertions.expression_is_true](https://github.com/mundipagg/amora-data-build-tool/commit/3b4ea413bcfd7ba5d6f0c1584f8baddb69d355d3)
> Corrige implementação de `amora.tests.assertions.expression_is_true`

- amora/cli.py
- amora/feature_store/config.py
`curl http://localhost:8666/list-feature-views | jq`
```json
[
{
"name": "step_count_by_source",
"features": [
"step_count_by_source:value_avg",
"step_count_by_source:value_sum",
"step_count_by_source:value_count"
],
"entities": [
"source_name"
]
}
]
```
> DTREX-613 Adds `amora feature-store serve` with an additional `GET /list-feature-views` resource

- pyproject.toml
- tests/feature_store/test_registry.py
- 🧪 Adds an unit test for `amora.feature_store.registry.get_feature_service`
- 🚀 `0.1.10rc3`
> DTREX-613 Adds an unit test for `amora.feature_store.registry.get_feature_service`

- amora/cli.py
- docs_src/cli.md
- examples/amora_project/feature_store.ipynb
-  📝 Adds an example jupyter notebook with examples of feature store usage at `examples/amora_project/feature_store.ipynb`
- 📝 Adds `amora feature-store serve` documentation
Notebook: https://github.com/mundipagg/amora-data-build-tool/blob/feature/DTREX-613-feature-service/examples/amora_project/feature_store.ipynb
> DTREX-613 feature store documentation

- poetry.lock
- pyproject.toml
ref: https://github.com/feast-dev/feast/issues/2484
obs.: Na versão 0.20.2 da feast isso já está configurado
> Configurando versão máxima de protobuf

- amora/cli.py
- poetry.lock
- pyproject.toml
- Adiciona prometheus-fastapi-instrumentator
- Expões métricas do Prometheus
> Expões métricas para Prometheus

- amora/compilation.py
- amora/providers/bigquery.py
- docs_src/cli.md
- docs_src/providers/bigquery.md
- examples/amora_project/models/array_repeated_field.py
- mkdocs.yml
- tests/providers/test_bigquery.py
- ✨ feat(bigquery): Adds support to repeated columns (ARRAY)
- ✨ feat(examples): Adds an example model that uses bigquery's arrays
- 📝 docs(bigquery): Adds amora.providers.bigquery documentation
- 🐛 fix(docs): Fixes CLI documentation code links
> DTREX-655 :: BigQuery ARRAY field support

- amora/compilation.py
- amora/providers/bigquery.py
- docs_src/providers/bigquery.md
- tests/providers/test_bigquery.py
- ✨ feat(bigquery): Enables UNNEST WITH OFFSET. 
- ✨ feat(bigquery): Adds `zip_arrays`
> DTREX-656 :: BigQuery `zip_arrays`

- amora/providers/bigquery.py
- pyproject.toml
- tests/providers/test_bigquery.py
> feat(bigquery): Enables selecting additional columns while using `zip_arrays`

- amora/providers/bigquery.py
- tests/providers/test_bigquery.py
More on: https://cloud.google.com/bigquery/docs/schemas
> fix(bigquery): Refactors `bigquery.get_schema_for_model` to support bigquery arrays

- amora/config.py
- amora/storage.py
- docs_src/api/storage.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
- tests/test_storage.py
- ✨ feat(storage): Adds `amora.storage.cache` decorator to cache functions that returns a `pandas.DataFrame`. Cache options are: `local` and `GCS`
- 📝 docs(storage): Adds `api/storage` docs page
> feat(storage): Adds `amora.storage.cache` decorator to cache functions that returns a `pandas.DataFrame`

- amora/dash/app.py
- amora/dash/components/materialization_badge.py
- amora/dash/components/materialization_type_badge.py
- amora/dash/components/model_code.py
- amora/dash/components/model_details.py
- amora/dash/components/model_summary.py
- amora/dash/pages/feature_store.py
- amora/dash/pages/models.py
- amora/meta_queries.py
- amora/models.py
- poetry.lock
- pyproject.toml
- ✨feat(dash): Adds [dash-ace](https://github.com/reasoned-ai/dash-ace) as an optional dependency
- ✨feat(dash): Adds components to render Python and SQL (compiled) code from an `AmoraModel`
- ✨feat(dash): Adds Accordion to `amora.dash.components.model_details`, with items: 
- DTREX-694 :: Summary, 
- DTREX-679 :: Python Code, 
- DTREX-674 :: SQL Code
- ✨feat(models): Adds `amora.models.model_path_for_model
- 🐛 fix(meta_queries): fixes missing import
- 🐛 fix(dash): Fixes feature_details component
💡 Ace code editor can be integrated with a language server. Read more: https://github.com/reasoned-ai/dash-ace#custom-auto-completer
---
> DTREX-674 DTREX-679 DTREX-680 :: amora[dash] :: `dash-ace` code editor

- amora/dash/config.py
- tests/providers/test_bigquery.py
- feat(dash): Uses SKETCHY as the default theme 
- tests(bigquery): Fixes broken test
> feat(dash): Uses `SKETCHY` as the default theme

- amora/dash/authentication.py
- amora/dash/components/model_labels.py
- amora/dash/config.py
- amora/dash/pages/feature_store.py
- amora/dash/pages/models.py
> amora[dash] :: Small fixes

- .github/workflows/main.yaml
- .github/workflows/pull-request.yaml
- poetry.lock
- pyproject.toml
- tests/test_meta_queries.py
Extraído de https://github.com/mundipagg/amora-data-build-tool/pull/165
> feat: Otimiza CI

- amora/cli/typer_app.py
- amora/dag.py
- amora/dash/components/model_columns.py
- amora/dash/components/model_datatable.py
- amora/dash/components/model_details.py
- amora/dash/pages/models.py
- amora/materialization.py
- amora/meta_queries.py
- amora/models.py
- amora/providers/bigquery.py
- amora/tests/generic_tests.py
- poetry.lock
- pyproject.toml
- tests/dash/pages/test_models.py
- tests/test_materialization.py
- tests/test_models.py
Extraído de https://github.com/mundipagg/amora-data-build-tool/pull/165
> feat: Torna amora compatível com Python 3.8

- amora/materialization.py
- tests/test_materialization.py
Adicionando apenas um delete_table para excluir automaticamente a tabela quando ela já estiver sido materializada como uma view, e precisarmos modificar para table.
> DTREX-716 <Adicionando `delete_table` quando a tabela for materializada

- LICENSE
> Fix: license typo

- amora/feature_store/__init__.py
- amora/feature_store/online_store.py
- pyproject.toml
https://github.com/feast-dev/feast/issues/3275
> fix: Force Feast to update Redis TTL

- amora/cli/feature_store.py
- amora/feature_store/feature_view.py
- tests/feature_store/test_decorators.py
Esse PR adiciona a possibilidade de exibir a descrição das FeatureViews
> feat: Adiciona description a FeatureView

- amora/cli/dash.py
- amora/dash/config.py
- amora/dash/gunicorn/application.py
- amora/dash/gunicorn/config.py
- amora/dash/metrics.py
- poetry.lock
- pyproject.toml
- tests/cli/dash/test_dash_serve.py
- deps: Adiciona gunicorn
- feat: Usa gunicorn em produção
> feat: gunicorn

- .github/workflows/main.yaml
- poetry.lock
- pyproject.toml
- chore: Extrai dependências de documentação para o grupo docs
- chore: Usa grupo docs para gerar documentação
> chore: Organiza pyproject.toml

- amora/dash/components/side_bar.py
Esse PR altera a tecla de acionamento do menu para `shift+m`
> chore: Altera tecla do menu para shift+m

- amora/dash/components/question_details.py
- amora/dash/pages/dashboard.py
- amora/questions.py
- amora/visualization.py
- tests/test_questions.py
> Adds support to dash heatmap viz

- amora/dash/metrics.py
- amora/feature_store/feature_view.py
- amora/models.py
- amora/providers/bigquery.py
- tests/dash/pages/test_feature_store.py
- tests/providers/test_bigquery.py
- refactor: Move get_fully_qualified_id para AmoraModel
- fix: Remove warning de um teste
- fix: Cria diretório de métricas automaticamente
> fix: Pequenas correções

- amora/cli/shared_options.py
- amora/cli/typer_app.py
- amora/utils.py
- tests/cli/test_materialize.py
feat: Adiciona flag --depends que quando passado um ou mais modelo, materializa todas as dependências (com excessão de tabelas importadas) dele.
> feat: Cria a possibilidade de materializar também os modelos dependentes de um modelo passado como referência
